### ISSUE TITLE
toggle.el causes "Recursive load"

### ISSUE THREAD

**Issue by tf** [zenspider/elisp#6]
Emacs 26.0.50.2:
```
defvar: Recursive load: "/home/___/.emacs.d/elpa/toggle-20160331.100/toggle.elc", ...
```

Looks like [this `toggle-style` call](https://github.com/zenspider/elisp/blob/164ae0f8302c1e1938a9e30597901b1164b43f96/toggle.el#L107) triggers auto loading.

**Comment by zenspider** [comment]
This should be fixed.
